set(_CATKIN_CURRENT_PACKAGE "runner")
set(runner_VERSION "0.0.0")
set(runner_MAINTAINER "pi <pi@todo.todo>")
set(runner_PACKAGE_FORMAT "2")
set(runner_BUILD_DEPENDS "geometry_msgs" "rospy")
set(runner_BUILD_EXPORT_DEPENDS "geometry_msgs" "rospy")
set(runner_BUILDTOOL_DEPENDS "catkin")
set(runner_BUILDTOOL_EXPORT_DEPENDS )
set(runner_EXEC_DEPENDS "geometry_msgs" "rospy")
set(runner_RUN_DEPENDS "geometry_msgs" "rospy")
set(runner_TEST_DEPENDS )
set(runner_DOC_DEPENDS )
set(runner_URL_WEBSITE "")
set(runner_URL_BUGTRACKER "")
set(runner_URL_REPOSITORY "")
set(runner_DEPRECATED "")