set(_CATKIN_CURRENT_PACKAGE "connector")
set(connector_VERSION "0.0.0")
set(connector_MAINTAINER "pi <pi@todo.todo>")
set(connector_PACKAGE_FORMAT "2")
set(connector_BUILD_DEPENDS "geometry_msgs" "rospy")
set(connector_BUILD_EXPORT_DEPENDS "geometry_msgs" "rospy")
set(connector_BUILDTOOL_DEPENDS "catkin")
set(connector_BUILDTOOL_EXPORT_DEPENDS )
set(connector_EXEC_DEPENDS "geometry_msgs" "rospy")
set(connector_RUN_DEPENDS "geometry_msgs" "rospy")
set(connector_TEST_DEPENDS )
set(connector_DOC_DEPENDS )
set(connector_URL_WEBSITE "")
set(connector_URL_BUGTRACKER "")
set(connector_URL_REPOSITORY "")
set(connector_DEPRECATED "")